// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/send-email": {
            "post": {
                "description": "Take the info and send email for you",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "Send email",
                "parameters": [
                    {
                        "description": "Email parameters",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/email.EmailParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "email.EmailParams": {
            "type": "object",
            "required": [
                "html",
                "owner",
                "subject",
                "to"
            ],
            "properties": {
                "html": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "\u003cp\u003eMessage description\u003c/p\u003e"
                },
                "owner": {
                    "type": "string",
                    "example": "maria@gmail.com"
                },
                "subject": {
                    "type": "string",
                    "maxLength": 120,
                    "example": "The message title"
                },
                "to": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "joaozinho@gmail.com"
                    ]
                }
            }
        },
        "swagger.APIError": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "integer"
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://sendemail.golembrar.com",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "goLembrar email service",
	Description:      "This microservice send the emails for you.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
