// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": [[ marshal .Schemes ]],
    "swagger": "2.0",
    "info": {
        "description": "[[escape .Description]]",
        "title": "[[.Title]]",
        "contact": {},
        "version": "[[.Version]]"
    },
    "host": "[[.Host]]",
    "basePath": "[[.BasePath]]",
    "paths": {
        "/check": {
            "get": {
                "description": "check if API is running",
                "tags": [
                    "main"
                ],
                "summary": "Health checker",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthCheckerResponse"
                        }
                    }
                }
            }
        },
        "/send-email": {
            "post": {
                "description": "take request and send the email for you",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "Send email",
                "parameters": [
                    {
                        "description": "Email parameters",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/email.EmailParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.EmailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "email.EmailParams": {
            "type": "object",
            "required": [
                "html",
                "owner",
                "subject",
                "to"
            ],
            "properties": {
                "html": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "\u003cp\u003eMessage description\u003c/p\u003e"
                },
                "owner": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "maria@gmail.com"
                },
                "subject": {
                    "type": "string",
                    "maxLength": 120,
                    "example": "The message title"
                },
                "to": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "joaozinho@gmail.com"
                    ]
                }
            }
        },
        "handler.EmailResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "cfb2011b..."
                },
                "message": {
                    "type": "string",
                    "example": "Email sent successfully"
                }
            }
        },
        "handler.HealthCheckerResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "swagger.APIError": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "integer"
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "goLembrar email microservice",
	Description:      "Dedicated microservice for send the emails for https://golembrar.com.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "[[",
	RightDelim:       "]]",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
