basePath: /v1
definitions:
  email.EmailParams:
    properties:
      html:
        example: <p>Message description</p>
        maxLength: 500
        type: string
      owner:
        example: maria@gmail.com
        type: string
      subject:
        example: The message title
        maxLength: 120
        type: string
      to:
        example:
        - joaozinho@gmail.com
        items:
          type: string
        type: array
    required:
    - html
    - owner
    - subject
    - to
    type: object
  swagger.APIError:
    properties:
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
host: https://sendemail.golembrar.com
info:
  contact: {}
  description: This microservice send the emails for you.
  title: goLembrar email service
  version: "1.0"
paths:
  /send-email:
    post:
      description: Take the info and send email for you
      parameters:
      - description: Email parameters
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/email.EmailParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/swagger.APIError'
      summary: Send email
      tags:
      - email
swagger: "2.0"
